# Generated by Django 3.0.6 on 2020-05-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20200523_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image_crop',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='person',
            name='jobcode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
