# Generated by Django 3.0.6 on 2020-06-01 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_event_logfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logfile',
            name='time',
        ),
    ]
