# Generated by Django 3.0.6 on 2020-06-01 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_auto_20200601_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='log_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.LogFile'),
        ),
    ]
