# Generated by Django 3.0.6 on 2020-06-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_event_log_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='body',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
